### ISSUE TITLE
Can this be used to flash Wyze devices with Tasmota?

### ISSUE THREAD

**Issue by oliverkurth** [HclX/WyzeUpdater#7]
I know the project https://github.com/elahd/wyze_plug_flasher makes use of this project to flash an intermediate firmware. And it worked, thank you!

But I was wondering, can this be used to flash Tasmota directly? And if not, why not?

**Comment by HclX** [comment]
Tasmota and wyze are using different OTA system and they are not compatible
so there has to be a conversion from one system to another. That's what the
intermediate firmware is doing. Since this is only needed once, I included
a copy of the firmware so you have everything you need I this repo to do
such conversion, no need to build the firmware yoyrself.

**Comment by oliverkurth** [comment]
Thank you! I didn't notice that you included the wyze_plug_flasher.bin, I used the one from https://github.com/elahd/wyze_plug_flasher .
